#!/usr/bin/env python3
"""
Generate a per-device DNS profile from a Pi-hole FTL DB.

For every client (LAN IP) in the lookback window, computes:
  - Total queries
  - Unique domains
  - Block ratio
  - Top 5 destinations (allowed)
  - Top 5 blocked destinations
  - Loudness verdict (ok / loud / very loud / suspicious)

Writes a markdown table you can drop straight into the writeup.

Usage:
    sudo python3 device_profile.py --hours 24 \\
        --names names.json \\
        --out ../../docs/03-analysis-device-table.md
"""
from __future__ import annotations

import argparse
import json
import sqlite3
import sys
import time
from pathlib import Path

# FTL "status" codes: 0/2 = forwarded/allowed, 1/4/5/6/7/9/10/11 = blocked
ALLOWED = {0, 2, 3, 12, 13, 14}
BLOCKED = {1, 4, 5, 6, 7, 8, 9, 10, 11, 15, 16, 17}


def loudness(qph: float, block_ratio: float, unique_domains: int) -> str:
    """Hand-tuned thresholds for a 24h window. Adjust to taste."""
    if qph > 1500:
        return "very loud"
    if qph > 400:
        return "loud"
    if block_ratio > 0.6 and qph > 50:
        return "suspicious"
    if unique_domains > 500:
        return "chatty"
    return "ok"


def load_names(p: Path | None) -> dict[str, str]:
    if not p or not p.exists():
        return {}
    return json.loads(p.read_text())


def fetch(db: Path, hours: int) -> list[tuple]:
    since = int(time.time()) - hours * 3600
    con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
    try:
        return list(
            con.execute(
                "SELECT timestamp, client, domain, status FROM queries WHERE timestamp >= ?",
                (since,),
            )
        )
    finally:
        con.close()


def build_profiles(rows: list[tuple], hours: int, names: dict[str, str]) -> list[dict]:
    from collections import Counter, defaultdict

    by_client: dict[str, dict] = defaultdict(lambda: {
        "total": 0, "blocked": 0, "domains": Counter(),
        "blocked_domains": Counter(), "first": None, "last": None,
    })
    for ts, client, domain, status in rows:
        c = by_client[client]
        c["total"] += 1
        c["first"] = ts if c["first"] is None else min(c["first"], ts)
        c["last"] = ts if c["last"] is None else max(c["last"], ts)
        if status in BLOCKED:
            c["blocked"] += 1
            c["blocked_domains"][domain] += 1
        else:
            c["domains"][domain] += 1

    out = []
    for client, c in by_client.items():
        total = c["total"]
        blocked = c["blocked"]
        ratio = blocked / total if total else 0
        unique = len(c["domains"]) + len(c["blocked_domains"])
        qph = total / hours if hours else 0
        out.append({
            "client": client,
            "name": names.get(client, ""),
            "total": total,
            "blocked": blocked,
            "block_ratio": ratio,
            "unique_domains": unique,
            "qph": qph,
            "top_allowed": c["domains"].most_common(5),
            "top_blocked": c["blocked_domains"].most_common(5),
            "verdict": loudness(qph, ratio, unique),
        })
    out.sort(key=lambda r: -r["total"])
    return out


def render(profiles: list[dict], hours: int) -> str:
    lines: list[str] = []
    lines.append(f"# Per-device DNS profile (last {hours}h)\n")
    lines.append(
        "Generated by `tools/device_profile/device_profile.py`. The "
        "`verdict` column is a hand-tuned heuristic, not a rule.\n"
    )
    lines.append(
        "| Client | Name | Queries | Blocked | Block % | Unique domains | "
        "Q/h | Verdict |"
    )
    lines.append(
        "|---|---|---:|---:|---:|---:|---:|---|"
    )
    for p in profiles:
        pct = f"{p['block_ratio'] * 100:.1f}%" if p["total"] else "—"
        lines.append(
            f"| `{p['client']}` | {p['name'] or '—'} | {p['total']} | "
            f"{p['blocked']} | {pct} | {p['unique_domains']} | "
            f"{p['qph']:.1f} | **{p['verdict']}** |"
        )
    lines.append("")
    lines.append("## Top destinations per client\n")
    for p in profiles:
        if not p["top_allowed"] and not p["top_blocked"]:
            continue
        header = f"### `{p['client']}`"
        if p["name"]:
            header += f" ({p['name']})"
        lines.append(header + "\n")
        if p["top_allowed"]:
            lines.append("**Allowed:**")
            lines.append("")
            for d, n in p["top_allowed"]:
                lines.append(f"- `{d}` — {n}")
            lines.append("")
        if p["top_blocked"]:
            lines.append("**Blocked:**")
            lines.append("")
            for d, n in p["top_blocked"]:
                lines.append(f"- `{d}` — {n}")
            lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", type=Path, default=Path("/etc/pihole/pihole-FTL.db"))
    ap.add_argument("--hours", type=int, default=24)
    ap.add_argument("--names", type=Path,
                    help="optional JSON map of {ip: friendly_name}")
    ap.add_argument("--out", type=Path,
                    help="write markdown to this file (default: stdout)")
    args = ap.parse_args()

    if not args.db.exists():
        print(f"[!] FTL DB not found: {args.db}", file=sys.stderr)
        return 2

    names = load_names(args.names)
    rows = fetch(args.db, args.hours)
    if not rows:
        print(f"[!] No queries in the last {args.hours}h.", file=sys.stderr)
        return 1

    profiles = build_profiles(rows, args.hours, names)
    md = render(profiles, args.hours)
    if args.out:
        args.out.write_text(md)
        print(f"[+] wrote {args.out}  ({len(profiles)} clients)")
    else:
        print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
